services:
  discovery-server:
    build: ./discovery-server
    image: lnr777/stratoshop-discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8761/eureka/apps" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratoshop-network

  api-gateway:
    build: ./api-gateway
    image: lnr777/stratoshop-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - stratoshop-network

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stratoshop_user_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratoshop-network

  user-service:
    build: ./user-service
    image: lnr777/stratoshop-user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/stratoshop_user_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      user-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - stratoshop-network

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stratoshop_product_db
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratoshop-network

  product-service:
    build: ./product-service
    image: lnr777/stratoshop-product-service:latest
    container_name: product-service
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://product-db:3306/stratoshop_product_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      product-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - stratoshop-network

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stratoshop_order_db
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratoshop-network

  order-service:
    build: ./order-service
    image: lnr777/stratoshop-order-service:latest
    container_name: order-service
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://order-db:3306/stratoshop_order_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      order-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - stratoshop-network

networks:
  stratoshop-network:
    driver: bridge
